create table if not exists public.shipment_imports (
    id bigint generated by default as identity primary key,

    legacy_shipment_id bigint not null,
    legacy_income_expense_id bigint,

    document_no text,
    despatch_date date,

    project_name text,

    supplier_name text,
    customer_name text,

    plate_number text,

    vehicle_working_type text,
    vehicle_master_group text,
    special_group text,

    service_income numeric(18,2) default 0,
    purchase_invoice_income numeric(18,2) default 0,
    sales_invoice_income numeric(18,2) default 0,

    raw jsonb not null,

    synced_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),

    constraint shipment_imports_legacy_unique
        unique (legacy_income_expense_id)
);

create index if not exists idx_shipment_imports_despatch_date
    on public.shipment_imports(despatch_date);

create index if not exists idx_shipment_imports_project
    on public.shipment_imports(project_name);

create index if not exists idx_shipment_imports_plate
    on public.shipment_imports(plate_number);

create index if not exists idx_shipment_imports_customer
    on public.shipment_imports(customer_name);