import { useMemo, useState } from "react";
import { AlertTriangle, CheckCircle2, Filter, FolderKanban, MoreVertical, Pencil, Plus, Search, ShieldCheck, Trash2, UserCheck, Users } from "lucide-react";
import { useEmployeeProjects } from "../features/employee-projects/useEmployeeProjects";
import { useActivateEmployee, useCreateEmployeeProject, useDeleteEmployee, useDeleteEmployeeProject, usePermanentDeleteEmployee, useUpdateEmployee, useUpdateEmployeeProject } from "../features/employee-projects/useEmployeeProjectMutations";
import type { EmployeeProjectEmployee } from "../features/employee-projects/types";
import { EditAllocationModal } from "../components/employee-projects/EditAllocationModal";
import { DeleteConfirmModal } from "../components/employee-projects/DeleteConfirmModal";
import { AddProjectModal } from "../components/employee-projects/AddProjectModal";
import { ProjectActionsMenu } from "../components/employee-projects/ProjectActionsMenu";
import { EmployeeProjectHistory } from "../components/employee-projects/EmployeeProjectHistory";
import { EditEmployeeModal } from "../components/employee-projects/EditEmployeeModal";
import { DeleteEmployeeConfirmModal } from "../components/employee-projects/DeleteEmployeeConfirmModal";

type StatusFilter = "all" | "complete" | "incomplete" | "active" | "passive";

export function EmployeeProjectsPage() {
  const { data, loading, error } = useEmployeeProjects();
  const createMutation = useCreateEmployeeProject(); const updateMutation = useUpdateEmployeeProject(); const deleteMutation = useDeleteEmployeeProject();
  const updateEmployeeMutation = useUpdateEmployee(); const deleteEmployeeMutation = useDeleteEmployee(); const activateEmployeeMutation = useActivateEmployee(); const permanentDeleteEmployeeMutation = usePermanentDeleteEmployee();
  const [search, setSearch] = useState(""); const [filter, setFilter] = useState<StatusFilter>("all"); const [openEmployeeMenu, setOpenEmployeeMenu] = useState<number | null>(null);
  const [editEmployee, setEditEmployee] = useState<{ id: number; name: string; username: string; is_active: boolean } | null>(null);
  const [deleteEmployee, setDeleteEmployee] = useState<{ id: number; name: string } | null>(null);
  const [editProject, setEditProject] = useState<{ id: number; name: string; current: number; max: number } | null>(null);
  const [deleteProject, setDeleteProject] = useState<{ id: number; name: string } | null>(null);
  const [addProjectOpen, setAddProjectOpen] = useState(false); const [selectedEmployeeId, setSelectedEmployeeId] = useState<number | undefined>();

  const employees = useMemo(() => {
    const needle = search.toLocaleLowerCase("tr-TR").trim();
    return (data?.employees ?? []).filter((employee) => {
      const matchesSearch = !needle || `${employee.name} ${employee.username} ${employee.projects.map((project) => project.project).join(" ")}`.toLocaleLowerCase("tr-TR").includes(needle);
      const matchesFilter = filter === "all" || (filter === "complete" && employee.totalPercentage === 100) || (filter === "incomplete" && employee.totalPercentage !== 100) || (filter === "active" && employee.is_active) || (filter === "passive" && !employee.is_active);
      return matchesSearch && matchesFilter;
    });
  }, [data, filter, search]);
  const completed = data?.employees.filter((item) => item.totalPercentage === 100).length ?? 0;
  const incomplete = (data?.employees.length ?? 0) - completed;

  function openAddProject(employeeId?: number) { setSelectedEmployeeId(employeeId); setAddProjectOpen(true); }
  function permanentlyDelete(employee: EmployeeProjectEmployee) {
    if (!window.confirm(`${employee.name} kullanıcısı ve tüm proje yetkileri kalıcı olarak silinecek. Bu işlem geri alınamaz. Devam edilsin mi?`)) return;
    permanentDeleteEmployeeMutation.mutate(employee.id); setOpenEmployeeMenu(null);
  }

  if (loading) return <LoadingState />;
  if (error) return <div className="rounded-3xl border border-red-200 bg-red-50 p-8 text-center"><AlertTriangle className="mx-auto h-8 w-8 text-red-500" /><h2 className="mt-3 font-black text-red-900">Proje yetkileri yüklenemedi</h2><p className="mt-1 text-sm text-red-700">{error}</p></div>;

  return <>
    <div className="space-y-6">
      <section className="relative overflow-hidden rounded-[30px] bg-gradient-to-br from-slate-950 via-slate-900 to-blue-950 p-7 text-white shadow-2xl shadow-slate-300/60">
        <div className="absolute -right-20 -top-20 h-64 w-64 rounded-full bg-blue-500/20 blur-3xl" />
        <div className="relative flex flex-col gap-5 lg:flex-row lg:items-end lg:justify-between"><div><div className="mb-3 inline-flex items-center gap-2 rounded-full border border-white/10 bg-white/10 px-3 py-1 text-xs font-bold text-blue-100"><ShieldCheck className="h-4 w-4" />Yetki ve kapasite merkezi</div><h1 className="text-3xl font-black tracking-tight">Proje Yetkileri</h1><p className="mt-2 max-w-2xl text-sm leading-6 text-slate-300">Kullanıcıların erişebileceği projeleri ve kapasite dağılımlarını tek ekrandan yönetin.</p></div><button type="button" onClick={() => openAddProject()} className="flex h-11 items-center justify-center gap-2 rounded-xl bg-blue-600 px-5 text-sm font-bold shadow-lg shadow-blue-950/30 transition hover:bg-blue-500"><Plus className="h-4 w-4" />Proje yetkisi ekle</button></div>
        <div className="relative mt-7 grid gap-3 sm:grid-cols-3"><Summary icon={Users} label="Toplam kullanıcı" value={data?.employees.length ?? 0} /><Summary icon={CheckCircle2} label="Dağılımı tamamlanan" value={completed} /><Summary icon={AlertTriangle} label="Düzenleme bekleyen" value={incomplete} /></div>
      </section>

      <section className="rounded-3xl border border-slate-200 bg-white p-4 shadow-lg shadow-slate-200/40">
        <div className="flex flex-col gap-3 lg:flex-row lg:items-center lg:justify-between"><div className="relative flex-1"><Search className="absolute left-3.5 top-1/2 h-4 w-4 -translate-y-1/2 text-slate-400" /><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Kullanıcı, kullanıcı adı veya proje ara..." className="h-11 w-full rounded-xl border border-slate-200 bg-slate-50 pl-10 pr-4 text-sm outline-none transition focus:border-blue-500 focus:bg-white focus:ring-4 focus:ring-blue-100" /></div><div className="flex items-center gap-2 overflow-x-auto"><Filter className="h-4 w-4 shrink-0 text-slate-400" />{([['all','Tümü'],['complete','Tamamlanan'],['incomplete','Eksik'],['active','Aktif'],['passive','Pasif']] as [StatusFilter,string][]).map(([value,label]) => <button type="button" key={value} onClick={() => setFilter(value)} className={`h-9 shrink-0 rounded-xl px-3 text-xs font-bold transition ${filter === value ? "bg-slate-950 text-white" : "bg-slate-100 text-slate-600 hover:bg-slate-200"}`}>{label}</button>)}</div></div>
        <div className="mt-3 flex items-center justify-between border-t border-slate-100 pt-3 text-xs text-slate-500"><span><b className="text-slate-900">{employees.length}</b> kullanıcı gösteriliyor</span>{search || filter !== "all" ? <button type="button" onClick={() => { setSearch(""); setFilter("all"); }} className="font-bold text-blue-600">Filtreleri temizle</button> : null}</div>
      </section>

      {employees.length ? <div className="grid items-start gap-5 xl:grid-cols-2">{employees.map((employee) => <EmployeeCard key={employee.id} employee={employee} menuOpen={openEmployeeMenu === employee.id} onMenu={() => setOpenEmployeeMenu((current) => current === employee.id ? null : employee.id)} onEditEmployee={() => { setEditEmployee({ id: employee.id, name: employee.name, username: employee.username, is_active: employee.is_active }); setOpenEmployeeMenu(null); }} onToggleEmployee={() => { if (employee.is_active) setDeleteEmployee({ id: employee.id, name: employee.name }); else activateEmployeeMutation.mutate(employee.id); setOpenEmployeeMenu(null); }} onPermanentDelete={() => permanentlyDelete(employee)} onAdd={() => openAddProject(employee.id)} onEditProject={setEditProject} onDeleteProject={setDeleteProject} />)}</div> : <div className="rounded-3xl border border-dashed border-slate-300 bg-slate-50 p-12 text-center"><Search className="mx-auto h-9 w-9 text-slate-300" /><h3 className="mt-3 font-black text-slate-900">Kullanıcı bulunamadı</h3><p className="mt-1 text-sm text-slate-500">Arama veya filtre kriterlerini değiştirin.</p></div>}
    </div>

    <EditAllocationModal open={Boolean(editProject)} projectName={editProject?.name ?? ""} current={editProject?.current ?? 0} max={editProject?.max ?? 0} loading={updateMutation.isPending} onClose={() => setEditProject(null)} onSave={async (percentage) => { if (!editProject) return; await updateMutation.mutateAsync({ id: editProject.id, percentage }); setEditProject(null); }} />
    <AddProjectModal open={addProjectOpen} employee={data?.employees.find((item) => item.id === selectedEmployeeId)} projects={data?.projects ?? []} loading={createMutation.isPending} onClose={() => { setAddProjectOpen(false); setSelectedEmployeeId(undefined); }} onSave={async (payload) => { await createMutation.mutateAsync(payload); setAddProjectOpen(false); setSelectedEmployeeId(undefined); }} />
    <DeleteConfirmModal open={Boolean(deleteProject)} projectName={deleteProject?.name ?? ""} loading={deleteMutation.isPending} onClose={() => setDeleteProject(null)} onConfirm={() => { if (!deleteProject) return; deleteMutation.mutate(deleteProject.id, { onSuccess: () => setDeleteProject(null) }); }} />
    <EditEmployeeModal open={Boolean(editEmployee)} employee={editEmployee} loading={updateEmployeeMutation.isPending} onClose={() => setEditEmployee(null)} onSave={(payload) => updateEmployeeMutation.mutate(payload, { onSuccess: () => setEditEmployee(null) })} />
    <DeleteEmployeeConfirmModal open={Boolean(deleteEmployee)} employeeName={deleteEmployee?.name ?? ""} loading={deleteEmployeeMutation.isPending} onClose={() => setDeleteEmployee(null)} onConfirm={() => { if (!deleteEmployee) return; deleteEmployeeMutation.mutate(deleteEmployee.id, { onSuccess: () => setDeleteEmployee(null) }); }} />
  </>;
}

function EmployeeCard({ employee, menuOpen, onMenu, onEditEmployee, onToggleEmployee, onPermanentDelete, onAdd, onEditProject, onDeleteProject }: { employee: EmployeeProjectEmployee; menuOpen: boolean; onMenu: () => void; onEditEmployee: () => void; onToggleEmployee: () => void; onPermanentDelete: () => void; onAdd: () => void; onEditProject: (value: { id: number; name: string; current: number; max: number }) => void; onDeleteProject: (value: { id: number; name: string }) => void }) {
  const complete = employee.totalPercentage === 100; const remaining = Math.max(0, 100 - employee.totalPercentage); const progress = Math.min(100, Math.max(0, employee.totalPercentage));
  return <article className={`overflow-hidden rounded-3xl border bg-white shadow-lg shadow-slate-200/40 transition hover:-translate-y-0.5 hover:shadow-xl ${employee.is_active ? "border-slate-200" : "border-slate-200 opacity-75"}`}>
    <header className="flex items-start justify-between gap-4 border-b border-slate-100 bg-slate-50/70 p-5"><div className="flex min-w-0 items-center gap-3"><span className={`grid h-12 w-12 shrink-0 place-items-center rounded-2xl text-lg font-black ${employee.is_active ? "bg-blue-100 text-blue-700" : "bg-slate-200 text-slate-500"}`}>{employee.name.slice(0,1).toLocaleUpperCase("tr-TR")}</span><div className="min-w-0"><div className="flex items-center gap-2"><h3 className="truncate font-black text-slate-950">{employee.name}</h3><span className={`rounded-full px-2 py-0.5 text-[10px] font-black ${employee.is_active ? "bg-emerald-100 text-emerald-700" : "bg-slate-200 text-slate-600"}`}>{employee.is_active ? "AKTİF" : "PASİF"}</span></div><p className="mt-1 truncate text-xs text-slate-500">@{employee.username} · {employee.projects.length} proje</p></div></div><div className="relative"><button type="button" onClick={onMenu} className="grid h-9 w-9 place-items-center rounded-xl border border-slate-200 bg-white text-slate-500 hover:bg-slate-100" aria-label="Kullanıcı işlemleri"><MoreVertical className="h-4 w-4" /></button>{menuOpen ? <div className="absolute right-0 z-30 mt-2 w-44 rounded-2xl border border-slate-200 bg-white p-2 shadow-xl"><MenuButton icon={Pencil} label="Kullanıcıyı düzenle" onClick={onEditEmployee} /><MenuButton icon={employee.is_active ? Trash2 : UserCheck} label={employee.is_active ? "Pasife al" : "Aktif et"} onClick={onToggleEmployee} tone={employee.is_active ? "red" : "green"} /><MenuButton icon={Trash2} label="Kalıcı olarak sil" onClick={onPermanentDelete} tone="red" /></div> : null}</div></header>
    <div className="p-5"><div className="grid grid-cols-[1fr_auto] items-end gap-4"><div><div className="flex items-center justify-between text-xs font-bold"><span className="text-slate-500">Toplam dağılım</span><span className={complete ? "text-emerald-700" : "text-amber-700"}>%{employee.totalPercentage}</span></div><div className="mt-2 h-2.5 overflow-hidden rounded-full bg-slate-100"><div className={`h-full rounded-full transition-all ${complete ? "bg-emerald-500" : progress >= 50 ? "bg-blue-500" : "bg-amber-500"}`} style={{ width: `${progress}%` }} /></div></div><div className={`rounded-2xl px-4 py-2 text-center ${complete ? "bg-emerald-50 text-emerald-700" : "bg-amber-50 text-amber-700"}`}><strong className="block text-xl font-black">%{remaining}</strong><span className="text-[10px] font-bold">KALAN</span></div></div>
      <div className="mt-5 space-y-2">{employee.projects.length ? employee.projects.map((project) => <div key={project.id} className="group rounded-2xl border border-slate-100 bg-slate-50 p-4 transition hover:border-blue-100 hover:bg-blue-50/50"><div className="flex items-start justify-between gap-3"><div className="min-w-0"><div className="flex items-center gap-2"><FolderKanban className="h-4 w-4 shrink-0 text-blue-600" /><p className="truncate text-sm font-black text-slate-800">{project.project}</p></div><div className="mt-3 h-1.5 overflow-hidden rounded-full bg-slate-200"><div className="h-full rounded-full bg-blue-500" style={{ width: `${Math.min(100, project.percentage)}%` }} /></div></div><div className="flex shrink-0 items-center gap-2"><span className="rounded-xl bg-white px-3 py-1.5 text-sm font-black text-blue-700 shadow-sm">%{project.percentage}</span><ProjectActionsMenu onEdit={() => onEditProject({ id: project.id, name: project.project, current: project.percentage, max: 100 - (employee.totalPercentage - project.percentage) })} onDelete={() => onDeleteProject({ id: project.id, name: project.project })} /></div></div></div>) : <div className="rounded-2xl border border-dashed border-slate-200 bg-slate-50 p-6 text-center"><FolderKanban className="mx-auto h-7 w-7 text-slate-300" /><p className="mt-2 text-sm font-bold text-slate-700">Henüz proje yetkisi yok</p></div>}</div>
      <button type="button" onClick={onAdd} disabled={remaining === 0} className="mt-4 flex h-11 w-full items-center justify-center gap-2 rounded-xl border border-dashed border-blue-300 text-sm font-bold text-blue-700 transition hover:bg-blue-50 disabled:cursor-not-allowed disabled:border-slate-200 disabled:text-slate-400"><Plus className="h-4 w-4" />{remaining === 0 ? "Dağılım tamamlandı" : `Proje ekle · %${remaining} kullanılabilir`}</button><EmployeeProjectHistory employeeId={employee.id} />
    </div>
  </article>;
}

function Summary({ icon: Icon, label, value }: { icon: typeof Users; label: string; value: number }) { return <div className="flex items-center gap-3 rounded-2xl border border-white/10 bg-white/10 p-4 backdrop-blur"><span className="grid h-10 w-10 place-items-center rounded-xl bg-white/10"><Icon className="h-5 w-5" /></span><div><strong className="block text-2xl font-black">{value}</strong><span className="text-xs font-bold text-slate-300">{label}</span></div></div>; }
function MenuButton({ icon: Icon, label, onClick, tone = "default" }: { icon: typeof Pencil; label: string; onClick: () => void; tone?: "default" | "red" | "green" }) { const color = tone === "red" ? "text-red-600 hover:bg-red-50" : tone === "green" ? "text-emerald-600 hover:bg-emerald-50" : "text-slate-700 hover:bg-slate-50"; return <button type="button" onClick={onClick} className={`flex w-full items-center gap-2 rounded-xl px-3 py-2 text-left text-xs font-bold ${color}`}><Icon className="h-4 w-4" />{label}</button>; }
function LoadingState() { return <div className="space-y-5"><div className="h-64 animate-pulse rounded-[30px] bg-slate-200" /><div className="h-20 animate-pulse rounded-3xl bg-slate-100" /><div className="grid gap-5 xl:grid-cols-2"><div className="h-96 animate-pulse rounded-3xl bg-slate-100" /><div className="h-96 animate-pulse rounded-3xl bg-slate-100" /></div></div>; }
